name: PR review

on:
  pull_request_review:
    types: [review_requested]
  pull_request:
    types: [submitted]

jobs:
  review_requested:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ":pray: A pull request review was requested: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}"
          SLACK_COLOR: "#C3996B" # or a specific color like 'good'
          MSG_MINIMAL: "true"

  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ":rocket: The pull request review has been approved: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}"
          SLACK_COLOR: "#219C61" # or a specific color like 'good'
          MSG_MINIMAL: "true"

  review_changes_requested:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ":skull_and_crossbones: Requested changes for pull request: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}"
          SLACK_COLOR: "#E24965" # or a specific color like 'good'
          MSG_MINIMAL: "true"

  pr_comment:
    if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ":speak_no_evil: A comment has been added to a pull request: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}"
          SLACK_COLOR: "#DADCDD" # or a specific color like 'good'
          MSG_MINIMAL: "true"
