name: PR review requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  review_requested:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ":rocket: A pull request review requested: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}"
          SLACK_COLOR: "#C3996B" # or a specific color like 'good'
          MSG_MINIMAL: "true"