name: Notify Slack on Pull Request Created
on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ":rocket: New pull request created: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}"
          SLACK_COLOR: '#219C61' # or a specific color like 'good'
          MSG_MINIMAL: true