name: Notify Slack on Pull Request Created
on:
  pull_request:
    types: [opened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        with:
          args: |
            {
              "webhook_url": "${{ secrets.SLACK_WEBHOOK }}",
              "message": "New pull request created: ${{ github.event.repository.html_url }}/pull/${{ github.event.pull_request.number }}",
              "channel": ${{ secrets.SLACK_CHANNEL_ID }},
              "username": "GitHub Bot",
              "icon_emoji": ":rocket:"
            }
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}